# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_94' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test_94

    pod 'Alamofire', '~> 4.7'
	pod 'SDWebImage', '~> 4.0'

end
